blogApp/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.views.static import serve
from app01 import views
from blogApp import settings

urlpatterns = [
    # 超级管理员
    path('admin/',admin.site.urls),
    # 首页  127.0.0.1:8000
    re_path('^$',views.index),
    # 首页  127.0.0.1:8000/index
    path('index/',views.index,name='index'),
    # 注册
    path('register/',views.sign_up,name='register'),
    # 登录
    path('login/',views.sign_in,name='login'),
    # 登出
    path('logout/',views.logout,name='logout'),
    # 验证码
    path('get_validCode_img/',views.get_validCode_img,name='static_image'),
    # 静态文件访问
    re_path(r"media/(?P<path>.*)$",serve,{"document_root":settings.MEDIA_ROOT}),
    # 点赞
    re_path("^article_up/$",views.article_up),
    # 评论
    re_path("^save_comment/$",views.article_comment),
    # 评论树
    re_path("^tree_comment/$",views.tree_comment),
    # 个人博客主页
    re_path("^(?P<username>\w+)/$",views.blog_mainPage),
    # 个人博客二级跳转
    re_path("^(?P<username>\w+)/(?P<condition>category|tag)/(?P<key>.*)/$",views.blog_mainPage),
    #文章详情
    re_path("^(?P<username>.*)/articles/(?P<article_id>.*)/$",views.article_detail),



]

app01/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
# Create your models here.


class User(AbstractUser):
    # 用户信息
    id = models.AutoField(primary_key = True)
    nickname = models.CharField(max_length=20,verbose_name="昵称",null=True)
    telephone = models.CharField(max_length=11,null=True,unique=True)
    email = models.EmailField()
    avatar = models.FileField(upload_to='avatars/', default="/static/image/default.jpg")
    create_time = models.DateField(verbose_name='创建时间',auto_now_add=True)
    blog = models.OneToOneField(to='Blog',to_field='id',on_delete=models.CASCADE,null=True)

    def __str__(self):
        return self.username


class Blog(models.Model):
    # 博客信息
    id = models.AutoField(primary_key = True)
    title = models.CharField(verbose_name='博客标题',max_length=99)
    site_name = models.CharField(verbose_name='站点名',max_length=99)

    def __str__(self):
        return self.title


class Category(models.Model):
    # 分类
    id = models.AutoField(primary_key = True)
    blogs = models.ForeignKey(verbose_name='所属博客',to='Blog',to_field='id',on_delete=models.CASCADE)
    title = models.CharField(verbose_name='标题',max_length=99)

    def __str__(self):
        return self.title


class Tag(models.Model):
    # 标签
    id = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称', max_length=32)
    blogs = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='id', on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Article(models.Model):
    # 文章
    id = models.AutoField(primary_key = True)
    title = models.CharField(max_length=50, verbose_name='文章标题')
    desc = models.CharField(max_length=255, verbose_name='文章描述')
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    content = models.TextField()
    comment_count = models.IntegerField(default=0)
    up_count = models.IntegerField(default=0)
    down_count = models.IntegerField(default=0)
    user = models.ForeignKey(verbose_name='作者', to='User', to_field='id', on_delete=models.CASCADE)
    category = models.ForeignKey(to='Category', to_field='id', null=True, on_delete=models.CASCADE)
    tags = models.ManyToManyField(to="Tag",through='Article_Tag',through_fields=('article', 'tags'),)

    def __str__(self):
        return self.title


class Article_Tag(models.Model):
    # 文章-标签关系表
    id = models.AutoField(primary_key = True)
    article = models.ForeignKey(to='Article',to_field='id',on_delete=models.CASCADE)
    tags = models.ForeignKey(to='Tag',to_field='id',on_delete=models.CASCADE)

    class Meta:
        unique_together = [('article','tags'),]

    def __str__(self):
        return self.article.title + '-----' + self.tags.title


class ArticleUpDown(models.Model):
    # 点赞表
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey('User', null=True, on_delete=models.CASCADE)
    article = models.ForeignKey("Article", null=True, on_delete=models.CASCADE)
    is_up = models.BooleanField(default=True)

    class Meta:
        unique_together = [
            ('article', 'user'),
        ]


class Comment(models.Model):
    # 评论表
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='评论文章', to='Article', to_field='id', on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='评论者', to='User', to_field='id', on_delete=models.CASCADE)
    content = models.CharField(verbose_name='评论内容', max_length=255)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    parent_comment = models.ForeignKey('self', null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

templates/article_detail.html
{% extends 'base_homesite.html' %}
{% block article_view %}
    <div class="blog-content-box">{{ article_view.content | safe}}</div>
    <!-- 点赞 -->
    <div class="more-toolbox" id="toolBarBox">
        <span id="fixedBar"></span>
        <div class="left-toolbox" style="position: relative; left: 0px; bottom: 0px; width: 900px;">
            <ul class="toolbox-list">
                <li class="tool-item tool-active is-like" id="is-like" >
                    <a>
                        <img style="display: none;" id="is-like-imgactive" src="https://csdnimg.cn/release/phoenix/template/new_img/tobarThumbUpactive.png" alt="">
                        <img style="display: block;" id="is-like-img" src="https://csdnimg.cn/release/phoenix/template/new_img/thumbUpWhite.png" alt="">
                        <span class="name" id="is-like-span"></span>
                        <span id="spanCount" class="count">{{ article_view.up_count }}</span>
                    </a>
                </li>
                <li class="tool-item tool-active tool-item-comment">
                    <a href="#commentBox">
                        <img src="https://csdnimg.cn/release/phoenix/template/new_img/commentWhite.png" alt="">
                        <span class="name">评论</span>
                        <span class="count"></span>
                    </a>
                </li>
                <li class="tool-item tool-active tool-QRcode" id="tool-share">
                    <a href="javascript:;" data-report-click="{&quot;mod&quot;:&quot;1582594662_002&quot;,&quot;ab&quot;:&quot;new&quot;}">
                        <img src="https://csdnimg.cn/release/phoenix/template/new_img/shareWhite.png" alt="">
                        <span class="name">分享</span>
                    </a>
                </li>
                <li class="tool-item tool-active is-collection ">
                    <a href="javascript:;" data-report-click="{&quot;mod&quot;:&quot;popu_824&quot;,&quot;ab&quot;:&quot;new&quot;}">
                        <img id="is-collection-img" style="display:block;" src="https://csdnimg.cn/release/phoenix/template/new_img/collectWhite.png" alt="">
                        <img id="is-collection-imgactive" style="display:none;" src="https://csdnimg.cn/release/phoenix/template/new_img/tobarCollectionActive.png" alt="">
                        <span class="name" id="is-collection">收藏</span>
                        <span class="count get-collection"></span>
                    </a>
                </li>
                <li class="tool-item tool-active tool-phong" id="tool-phong">
                    <a href="javascript:;" data-report-click="{&quot;mod&quot;:&quot;popu_831&quot;,&quot;dest&quot;:&quot;&quot;,&quot;ab&quot;:&quot;new&quot;}">
                        <img src="https://csdnimg.cn/release/phoenix/template/new_img/mobileWhite.png" alt="">
                        <span class="name">手机看</span>
                    </a>
                </li>
                <!--打赏开始-->
                <li class="tool-item tool-active tool-reward" id="toolreward">
                    <a data-report-click="{&quot;mod&quot;:&quot;popu_830&quot;,&quot;dest&quot;:&quot;&quot;,&quot;ab&quot;:&quot;new&quot;}"><img src="https://csdnimg.cn/release/phoenix/template/new_img/rewardWhite.png" alt=""><span class="name">打赏</span></a>
                </li>
                <!--打赏结束-->
                <li class="tool-item tool-active tool-more">
                    <!-- <a>
                    <img src="https://csdnimg.cn/release/phoenix/template/new_img/lookMore.png" alt="">
                    </a>
                    <ul class="more-box">
                        <li class="item"><a class="article-report">文章举报</a></li>
                    </ul> -->
                    <a class="article-report">文章举报</a>
                </li>
            </ul>
            <div style="display:flex">
                <a class="tool-mover-open" id="btn-readmore" style="display: none;" data-type="0" data-report-click="{&quot;mod&quot;:&quot;popu_376&quot;,&quot;dest&quot;:&quot;https://blog.csdn.net/weixin_42494845/article/details/106343111&quot;,&quot;strategy&quot;:&quot;packupbar&quot;,&quot;ab&quot;:&quot;new&quot;}" height="3">
                    <span>收起全文</span>
                    <img id="btn-close-img" style="display: block;" src="https://csdnimg.cn/release/phoenix/template/new_img/CommentArrow.png" alt="">
                </a>
            </div>
        </div>
    </div>
    <!-- 点赞end -->
    <!-- 评论 -->
    <div class="comment-box">
        <div class="comment-edit-box d-flex" >
            <a id="commentsedit"></a>
            <div class="user-img" style="display: inline-block">
                <a rel="noopener">
                    <img class="" src="media/{{ login_user.avatar }}">
                </a>
            </div>
            <form id="commentform" style="display: inline-block">
                <textarea class="comment-content open" name="comment_content" id="comment_content" placeholder="优质评论可以帮助作者获得更高权重" maxlength="1000"></textarea>
                <div class="opt-box"> <!-- d-flex -->
                    <div id="ubbtools" class="add_code">
                        <a target="_self"><i class="icon iconfont icon-daima"></i></a>
                    </div>
                    <input type="hidden" id="comment_replyId" name="comment_replyId">
                    <input type="hidden" id="article_id" name="article_id" >
                    <input type="hidden" id="comment_userId" name="comment_userId">
                    <input type="hidden" id="commentId" name="commentId" >
                </div>
            </form>
        </div>
        <div style="margin-left: 790px">
            <input type="button" class="bt-comment-empty" value="取消评论">
            <input type="button" class="bt-comment-show" value="评论">
        </div>
        <!-- 评论树 -->
        {% include 'tree_comment.html' %}
        <!-- 评论树end -->
    </div>
    <!-- 评论end -->
{% endblock %}

templates/aside_homesite.html
<div>
    <div class="panel panel-danger">
        <div class="panel-heading">最新文章</div>
        <div class="panel-body">
            {% for article in top_list %}
                {% if forloop.counter0 <= 4  %}
                    <a href="/{{ article.user }}/articles/{{ article.id }}" target="_blank">
                        {{article.title}}
                    </a>
                    <br>
                {% endif %}
            {% endfor %}
        </div>
    </div>
    <div class="panel panel-danger">
        <div class="panel-heading">分类专栏</div>
        <div class="panel-body">
            {% for tag_obj in tag_list %}
                <div>
                    <a href="/{{ user.username }}/tag/{{ tag_obj.id }}" target="_blank">
                        <span class="float-left">{{ tag_obj.title }}</span>
                    </a>
                    <small class="float-right">{{ tag_obj.c }}篇</small>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

templates/base_homesite.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.css">
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap-theme.css">
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <script src="/static/jquery-3.5.0.min.js"></script>
    <script src="/static/bootstrap-3.3.7-dist/js/bootstrap.js"></script>
    <link rel="stylesheet" href="/static/blog/css/index.css">
    <link rel="stylesheet" href="/static/blog/css/article_detail.css">
    <link rel="stylesheet" href="/static/blog/css/article_comment.css">
</head>
<body>
<script src="/static/jquery-3.5.0.min.js"></script>
<script src="/static/bootstrap-3.3.7-dist/js/bootstrap.js"></script>
<header>
    <div class="container d-flex " style="">
        <div class="title-box">
            <h1 class="title-blog">
                <a href="https://blog.csdn.net/leetaking">{{ user.username }}的博客</a>
            </h1>
            <p class="description "></p>
        </div>
    </div>
</header>

<script>
$(function () {
    //默认点赞
    if("{{ updown_obj.is_up }}"){
        $("#is-like-imgactive").css("display","block");
        $("#is-like-img").css("display","none");
        $("#is-like-span").html("已赞")
    }else {
        $("#is-like-span").html("点赞")
    }
    //点赞
    $("#is-like a").click(function () {
        $.ajax({
            url: '/article_up/',
            type: 'post',
            data: {
                article_id: {{ article_view.id }},
                csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val()
            },
            success:function (data) {
                var up_count = parseInt($("#spanCount").text());
                if(data.status){
                    $("#is-like-imgactive").css("display","block");
                    $("#is-like-img").css("display","none");
                    $("#is-like-span").html("已赞");
                    $("#spanCount").text(up_count+1)
                }else {
                    $("#is-like-imgactive").css("display","none");
                    $("#is-like-img").css("display","block");
                    $("#is-like-span").html("点赞");
                    $("#spanCount").text(up_count-1)
                }
            }
        })
    });
    //提交评论
    $(".bt-comment-show").click(function () {
        $.ajax({
            url: "/save_comment/",
            data: {
                parent_comment: $("#commentId").val(),
                content: $("#comment_content").val(),
                article_id: {{ article_view.id }},
                csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val()
            },
            success:function (data) {
                //刷新评论树
                $(".comment-list-box").load("/tree_comment/",{"article_id":data.article_id, "csrfmiddlewaretoken": $("[name='csrfmiddlewaretoken']").val()})
            },
            error:function () {
                alert('ajax回调错误')
            }
        })
    });
    //取消评论
    $(".bt-comment-empty").click(function () {
        $("#comment_content").attr("placeholder","想跟作者说点什么..").val("");
        $("#commentId").val("")
    });

});
</script>
<div class="container-fluid">
    {%csrf_token%}
    <div class="row">
        <div class="col-md-3">
            <!-- 用户信息 -->
            {% block profile %}
            {% endblock %}
            <!-- 侧边栏 -->
            {% load aside_home %}
            {% get_aside_style user %}
            <div class="panel panel-danger">
                <div class="panel-heading">热门文章</div>
                <div class="panel-body">......</div>
            </div>
        </div>
        <div class="col-md-9">
            <!-- 文章列表 -->
            {% block list %}
            {% endblock %}
            <!-- 文章详情 -->
            <main>
            {% block article_view %}
            {% endblock %}
            </main>
        </div>
    </div>
</div>
</body>
</html>

templates/foot.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
</head>
<body>
<div class="footer">
    底部内容
</div>
</body>
</html>

templates/homesite.html
{% extends 'base_homesite.html' %}
{% block profile %}
    <div class="panel panel-danger">
        <div>
            <div class="avatar-box">
                <img width="48px" height="48px" src="media/{{ user.avatar }}" alt="">
                {{ user.nickname }}
            </div>
        </div>
    </div>
{% endblock %}
{% block list %}
    {% for article in article_list %}
        <div class="clearfix">
            <h3><a href="/{{ user.username }}/articles/{{ article.id }}" target="_blank">{{ article.title }}</a></h3>
            <p><a href="/{{ user.username }}/articles/{{ article.id }}" target="_blank">{{ article.desc }}</a></p>
            <div class="small pub_info pull-left">
                <p>
                    <span>发布于 &nbsp;&nbsp;{{ article.create_time }}</span>
                </p>
            </div>
        </div>
        <br>
    {% endfor %}
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.css">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>博客</title>
    <style>
        .navbar-header .navbar-brand{
            padding: 0 0;
        }
    </style>
</head>

<body>
<script src="/static/jquery-3.5.0.min.js"></script>
<script src="/static/bootstrap-3.3.7-dist/js/bootstrap.js"></script>
{%csrf_token%}
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href=""><img width="45" height="45" alt="Brand" src="/static/image/FAAM.jpg"></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="#">博客</a></li>
                <li><a href="#">学院</a></li>
                <li><a href="#">下载</a></li>
                <li><a href="#">新闻</a></li>
                <li><a href="#">招聘</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><img width="28" height="28" src="media/{{ request.user.avatar }}" alt="..."><span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">我的关注</a></li>
                            <li><a href="#">我的博客</a></li>
                            <li><a href="#">我的学院</a></li>
                            <li><a href="/logout/">退出</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}">登录</a></li>
                    <li><a href="{% url 'register' %}">注册</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-danger">
                <div class="panel-heading">面板A</div>
                <div class="panel-body">面板A内容</div>
            </div>
        </div>
        <!--文章列表 -->
        <div class="col-md-6">
            {% for foo in art_list %}
                <div>
                    <a href="/{{ foo.user }}/articles/{{ foo.id }}" target="_blank"><h3>{{ foo.title }}</h3></a>
                </div>
                <div><small>{{ foo.desc }}</small></div>
                <div class="media-left">
                    <span>
                        <img width="22" height="22" src="media/{{ foo.user.avatar }}" alt="">
                        <a href="/{{ foo.user.username }}" target="_blank">{{ foo.user.username }}</a>
                    </span>
                </div>
                <div class="media-right"></div>
                <hr>
            {% endfor %}
        </div>
        <div class="col-md-3">
            <div class="panel panel-primary">
                <div class="panel-heading">主面板B</div>
                <div class="panel-body">面板B内容</div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.css">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>博客登录</title>
</head>
<body>
<script src="/static/jquery-3.5.0.min.js"></script>
<script src="/static/bootstrap-3.3.7-dist/js/bootstrap.js"></script>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-lg-offset-3">
            <form action="{% url 'login' %}" method="post">
                {%csrf_token%}
                <div class="form-group">
                    <label for="username">用户:</label>
                    <input type="text" class="form-control" id="username" name="username">
                </div>
                <div class="form-group">
                    <label for="password">密码:</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>
                <div class="form-group">
                    <label for="valid_code">验证码</label>
                    <div class="row">
                        <div class="col-md-6">
                            <input type="text" class="form-control" id="valid_code">
                        </div>
                        <div class="col-md-6">
                            <img width="160" height="36" id="valid_code_img" src="{% url 'static_image' %}" alt="">
                        </div>
                    </div>
                </div>
                <input type="button" class="btn btn-default login_btn" value="登录"><span class="error"></span>
                <a href="{% url 'register' %}" class="btn btn-success pull-right">注册</a>
            </form>
        </div>
    </div>
</div>
<script>
    $("#valid_code_img").click(function () {
        $(this)[0].src += "?"
    });
    $(".login_btn").click(function (){
        $.ajax({
            url: "",
            type: "post",
            data: {
                username:$("#username").val(),
                password:$("#password").val(),
                valid_code:$("#valid_code").val(),
                csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val()
            },
            success: function (data) {
                console.log(data);
                if (data.user) {
                    location.href="/index/"
                } else {
                    $(".error").text(data.msg).css({"color": "red", "margin-left": "10px"});
                    setTimeout(function () {
                        $(".error").text("");
                    }, 50000)
                }
            }
        })
    })
</script>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.css">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
</head>
<body>
<script src="/static/jquery-3.5.0.min.js"></script>
<script src="/static/bootstrap-3.3.7-dist/js/bootstrap.js"></script>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-lg-offset-3">
            <form id="form" action="{% url 'register' %}">
                {%csrf_token%}
                {% for d in form %}
                    <div class="form-group">
                        {{ d.label }}{{ d }}<span class="error pull-right"></span>
                    </div>
                {% endfor %}
                <div><span>{{ error_msg.0 }}</span></div>
                <div class="form-group">
                    <label for="avatar">头像<img src="/static/image/default.jpg" alt="" style="width: 100px;height: 100px"></label>
                    <input type="file" id="avatar">
                </div>
                <input type="button" class="btn btn-default login_btn" value="注册">
            </form>
        </div>
    </div>
</div>
<script>
    $("#avatar").change(function () {
        var obj = $(this)[0].files[0];
        var file = new FileReader();   // 文件读取器
        file.readAsDataURL(obj);  // 取得头像的url，返回结果file.result
        file.onload = function () {
            $("img").attr("src",file.result)
        }
    });

    $("input[type='button']").click(function () {
        var formdata = new FormData();
        {#formdata.append("username",$("#id_username").val());#}
        {#formdata.append("password",$("#id_password").val());#}
        {#formdata.append("confirm_password",$("#id_confirm_password").val());#}
        {#formdata.append("telephone",$("#id_telephone").val());#}
        {#formdata.append("email",$("#id_email").val());#}
        {#formdata.append("csrfmiddlewaretoken",$("[name='csrfmiddlewaretoken']").val());#}
        {#formdata.append("avatar",$("#avatar")[0].files[0]);#}
        var form_data = $("#form").serializeArray();
        $.each(form_data,function (index,data) {
            formdata.append(data.name,data.value)
        });
        formdata.append("avatar",$("#avatar")[0].files[0]);
        $.ajax({
            url:'',
            type:'post',
            data:formdata,
            processData:false,
            contentType:false,
            success:function (data) {
                if(data.user){
                    console.log(data);
                    location.href="/login/"
                }
                else if (data.msg){
                    $("span.error").html("");
                    $(".form-group").removeClass("has-error");
                    $.each(data.msg,function (field,error_list) {
                        if (field === "__all__"){
                            $("#id_confirm_password").next().html(error_list[0]).parent().addClass("has-error");
                        }
                        $("#id_"+ field).next().html(error_list[0]).parent().addClass("has-error");
                    })
                }
            }
        })
    })
</script>
</body>
</html>

templates/tree_comment.html
<script>
    function reply(comment_id,name) {
        $("#commentId").val(comment_id);
        $("#comment_content").attr("placeholder","回复："+name).focus()
    }
</script>
<div class="comment-list-container" style="display: block;">
    {%csrf_token%}
    <div class="comment-list-box" >
        {% for comment in comment_list.items %}
            <ul class="comment-list">
                <li class="comment-line-box d-flex" >
                    <a target="_blank" href="" style="display: inline-block">
                        <img style="width: 28px;height: 28px; border-radius: 50%" src="media/{{ comment.1.user.avatar }}" class="avatar">
                    </a>
                    <div class="right-box" style="display: inline-block;width: 90%">
                        <div class="new-info-box clearfix">
                            <a><span class="name ">{{ comment.1.user.nickname }}:</span></a>
                            <div class="new-comment">{{ comment.1.content }}</div>
                            <span class="date" title="2020-06-13 16:45:36"></span>
                            <span style="float: right" onclick="reply('{{ comment.0 }}','{{ comment.1.user.nickname }}')">回复</span>
                        </div>
                    </div>
                </li>
                <li class="replay-box">
                    <ul class="comment-list">
                        {% for son_comment in comment.1.son_comment %}
                        <li class="comment-line-box d-flex">
                            <a target="_blank" style="display: inline-block">
                                <img style="width: 28px;height: 28px; border-radius: 50%" src="media/{{ son_comment.user.avatar }}" class="avatar">
                            </a>
                            <div class="colon" href="">{{ son_comment.user.nickname }} 回复&nbsp;{{ comment.1.user.nickname }}:&nbsp; <span class="new-comment">{{ son_comment.content }}</span></div>
                        </li>
                        {% endfor %}
                    </ul>
                </li>

            </ul>
        {% endfor %}
    </div>
</div>